version: '3.8'
services:
  db:
    image: postgres:15
    container_name: oauth_training_db
    environment:
      POSTGRES_USER: oauth_user
      POSTGRES_PASSWORD: oauth_pass
      POSTGRES_DB: oauth_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: oauth_training_backend
    depends_on: [db]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: oauth_user
      DB_PASSWORD: oauth_pass
      DB_NAME: oauth_db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
      - /app/tmp
    ports:
      - "8080:8080"
    command: ["air"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: oauth_training_frontend
    depends_on: [backend]
    environment:
      VITE_API_URL: http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

volumes:
  db_data:
networks:
  default:
    driver: bridge